faceattendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls.static import static
from django.conf import settings

from misweb.views import (
    DashboardView,
    DaftarHadirView,
    ListPegawaiView,
    PengaturanView,
    TambahPegawaiView,
    EditPegawaiView,
    delete_model,
    TestView,
    TestApiView,
    AbsensiApiView,
    AbsensiSayaView
    )


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', TestView.as_view(), name='test'),
    path('daftar-hadir/', DaftarHadirView.as_view(), name='daftar-hadir'),
    path('absensi-saya/', AbsensiSayaView.as_view(), name='absensi-saya'),

    path('list-pegawai/', ListPegawaiView.as_view(), name='list-pegawai'),
    path('tambah-pegawai/', TambahPegawaiView.as_view(), name='tambah-pegawai'),
    path('edit-pegawai/<pk>/', EditPegawaiView.as_view(), name='edit-pegawai'),
    path('hapus-pegawai/<pk>/', delete_model, name='hapus-pegawai'),

    path('test-api-view/<pk>/', TestApiView.as_view()),
    path('absensi-api-view/', AbsensiApiView.as_view()),

    path('pengaturan/<pk>/', PengaturanView.as_view(), name='pengaturan'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misweb/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin, BaseUserManager
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
import datetime

import os



def image_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{instance.nip}.jpg'

    return os.path.join('faceimg', filename)


class EmployeeManager(BaseUserManager):
    """Manager for user profiles"""

    def create_user(self, nip, name, image, password=None):
        """Create a new user profiles"""
        if not nip:
            raise ValueError('NIP tidak valid')

        user = self.model(nip=nip, name=name, image=image)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, nip, name, image, password):
        """Create a new superuser with given details"""
        user = self.create_user(nip, name, image, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user


class Employee(AbstractBaseUser, PermissionsMixin):
    """Database model for users in the system"""
    nip = models.IntegerField(unique=True)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to = image_path)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = EmployeeManager()

    USERNAME_FIELD = 'nip'
    REQUIRED_FIELDS = ['name', 'image']

    def get_full_name(self):
        """Retrieve full name of user"""
        return self.name

    def get_short_name(self):
        """Retrieve short name of user"""
        return self.name

    def __str__(self):
        """Return string representation of our user"""
        return self.name
    
    def delete_url(self):
        return reverse('hapus-pegawai', kwargs={'pk': self.id})

class Kamera(models.Model):
    """Handle attendance"""
    apikey = models.CharField(max_length=255)
    nama_kamera = models.CharField(max_length=255)
    periode_absensi = models.TextField()
    min_face_size = models.IntegerField()
    face_threshold = models.DecimalField(decimal_places=2, max_digits=4)
    true_threshold = models.DecimalField(decimal_places=2, max_digits=4)
    input_width = models.IntegerField()
    input_height = models.IntegerField()

    def __str__(self):
        return self.nama_kamera

class Absensi(models.Model):
    """Handle attendance"""
    employee = models.ForeignKey("misweb.Employee", on_delete=models.CASCADE)
    kamera = models.ForeignKey("misweb.Kamera", on_delete=models.CASCADE, default=-1)
    first_seen = models.DateTimeField(auto_now=False, default=timezone.now)
    last_seen = models.DateTimeField(auto_now=False, default=timezone.now)

    def __str__(self):
        return self.employee.name

misweb/forms.py
from django import forms
from django.forms import widgets
from .models import Employee, Kamera 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
 
# creating a form
class EmployeeForm(UserCreationForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Employee
        # specify fields to be used
        fields = [
            'nip',
            'name',
            'image',
        ]

class EditEmployeeForm(UserChangeForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Employee
        # specify fields to be used
        fields = [
            'is_staff',
            'nip',
            'name',
            'image',
        ]

class KameraForm(forms.ModelForm):

    class Meta:
        model = Kamera
        fields = [
            'periode_absensi',
            'min_face_size',
            'face_threshold',
            'true_threshold',
            'input_width',
            'input_height',
        ]

misweb/views.py
from .forms import KameraForm, EmployeeForm, EditEmployeeForm
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView

from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import JsonResponse
from django.urls import reverse_lazy

import datetime, json

from misweb import serializers
from rest_framework import status, viewsets, filters
from rest_framework.views import APIView
from rest_framework.response import Response


from .models import Employee, Absensi, Kamera
# from .forms import LoginForm
from django.apps import apps

class Itterasi():
    pengaturan_itter = 1
    pegawai_itter = 0

class TestApiView(APIView):
    """Test API View"""
    serializer_class = serializers.TestSerializer

    def get(self, request, pk):
        """Returns a list of APIView features"""
        for_kamera = Kamera.objects.filter(id=pk).last()
        periode = json.loads(for_kamera.periode_absensi)

        karyawan_state = True
        for_karyawan = Employee.objects.values_list('nip', flat=True)

        cam_dict = {
            "pengaturan": Itterasi.pengaturan_itter,
            "parameter": {
                "jadwal": periode,
                'min_face_size': for_kamera.min_face_size,
                'face_threshold': for_kamera.face_threshold,
                'true_threshold': for_kamera.true_threshold,
                'input_width': for_kamera.input_width,
                'input_height': for_kamera.input_height
            },
            'karyawan': Itterasi.pegawai_itter,
            'nip': for_karyawan
        }

        return Response(cam_dict)


class AbsensiApiView(APIView):
    """Test API View"""
    serializer_class = serializers.AbsensiSerializer

    def get(self, request, format=None):
        absen = Absensi.objects.values_list('id', 'employee', 'first_seen')
        return Response({'absen': absen})
        
    def post(self, request):
        """Create a hello message with our name"""
        nip_peg = request.data.get('employee')
        id_peg_obj = Employee.objects.filter(nip=nip_peg).last()
        apikey_cam_obj = Kamera.objects.filter(id=request.data.get('kamera')).last()
        if id_peg_obj is not None and apikey_cam_obj is not None:
            id_peg = id_peg_obj.id
            apikey_cam = apikey_cam_obj.apikey
            data = {'employee':id_peg, 'kamera':request.data.get('kamera')}
            serializer = self.serializer_class(data=data)
            apikey_validation = request.data.get('apikey')

            if serializer.is_valid() and apikey_cam == apikey_validation:
                nama_pegawai = serializer.validated_data.get('employee')
                id_absen = Absensi.objects.filter(employee=nama_pegawai, first_seen__date=datetime.datetime.now())

                if id_absen.exists():
                    absen_object = Absensi.objects.get(id=id_absen.last().id)
                    absen_object.last_seen = datetime.datetime.now()
                    absen_object.save()

                    testnip = serializer.validated_data.get('employee').nip
                    message = f'Save exist {absen_object.id}, request.data = {testnip}'
                    return Response({'message': message})
                    
                else:
                    serializer.save()
                    message = f'Exist? {id_absen}, request.data = {serializer.validated_data}'
                    return Response({'message': message})
            else:
                return Response(
                    serializer.errors,
                    status=status.HTTP_400_BAD_REQUEST
                )
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)

class TestView(TemplateView):
    """To Dashboard Page"""

    template_name = "test.html"


class DashboardView(TemplateView):
    """To Dashboard Page"""

    template_name = "dashboard.html"

    def get(self, request):
        tanggal = datetime.datetime.now()
        list_absensi = Absensi.objects.filter(first_seen__date=tanggal)
        list_pegawai = Employee.objects.all()
        jml_pegawai = list_pegawai.count()
        jml_absensi = list_absensi.count()
        rasio = (jml_absensi/jml_pegawai)*100

        statusAbsensi=[]
        for pegawai in list_pegawai:
            status = list_absensi.filter(employee=pegawai.id)
            nama = pegawai.name
            statusAbsensi.append(StatusPegawai(status=status.exists(), nama=nama, id_absensi=status.last()))
                    
        context={
            'list_absensi': list_absensi,
            'hari_ini': tanggal,
            'list_pegawai': statusAbsensi,
            'rasio': rasio,
            'jml_pegawai': jml_pegawai,
            'jml_absensi': jml_absensi,
        }
        return render(request, self.template_name, context)


class DaftarHadirView(TemplateView):
    """To Page Daftar Hadir"""

    template_name = "daftar-hadir.html"

    def post(self, request):
        tanggal = request.POST.get('tanggal')
        list_absensi = Absensi.objects.filter(first_seen__date=tanggal)
        list_pegawai = Employee.objects.all()
        
        statusAbsensi=[]
        for pegawai in list_pegawai:
            status = list_absensi.filter(employee=pegawai.id)
            nama = pegawai.name
            statusAbsensi.append(StatusPegawai(status=status.exists(), nama=nama, id_absensi=status.last()))

        context={
            'list_absensi': list_absensi,
            'hari_ini': tanggal,
            'list_pegawai': statusAbsensi,
        }
        return render(request, self.template_name, context)

    def get(self, request):
        tanggal = datetime.datetime.now()
        list_absensi = Absensi.objects.filter(first_seen__date=tanggal)
        list_pegawai = Employee.objects.all()

        statusAbsensi=[]
        for pegawai in list_pegawai:
            status = list_absensi.filter(employee=pegawai.id)
            nama = pegawai.name
            statusAbsensi.append(StatusPegawai(status=status.exists(), nama=nama, id_absensi=status.last()))

        context={
            'list_absensi': list_absensi,
            'hari_ini': tanggal,
            'list_pegawai': statusAbsensi,
        }
        return render(request, self.template_name, context)


class AbsensiSayaView(TemplateView):
    """To Page Daftar Hadir"""

    template_name = "absensi-saya.html"

    def get(self, request):
        tanggal = datetime.datetime.now()
        list_absensi = Absensi.objects.filter(first_seen__date=tanggal)
        list_pegawai = Employee.objects.all()

        statusAbsensi=[]
        for pegawai in list_pegawai:
            status = list_absensi.filter(employee=pegawai.id)
            nama = pegawai.name
            statusAbsensi.append(StatusPegawai(status=status.exists(), nama=nama, id_absensi=status.last()))

        context={
            'list_absensi': list_absensi,
            'hari_ini': tanggal,
            'list_pegawai': statusAbsensi,
        }
        return render(request, self.template_name, context)


class ListPegawaiView(TemplateView):
    """To Page Daftar Hadir"""

    template_name = "list-pegawai.html"

    def get(self, request):
        list_pegawai = Employee.objects.all()
        context={
            'list_pegawai': list_pegawai,
        }
        return render(request, self.template_name, context)


class TambahPegawaiView(CreateView):
    # specify the model for create view
    template_name = 'misweb/employee_form.html'
    success_url = reverse_lazy('list-pegawai')
    form_class = EmployeeForm

    def post(self, request):
        form = EmployeeForm(request.POST, request.FILES)
        print(form.errors)

        if form.is_valid():
            print("valid")
            Itterasi.pegawai_itter = Itterasi.pegawai_itter + 1
            form.save()

        context={
            'form': EmployeeForm,
        }
        return redirect(self.success_url)


class EditPegawaiView(FormView):
    # specify the model you want to use
    success_url = '/list-pegawai/'
    template_name = 'misweb/employee_update_form.html'
    form_class = EditEmployeeForm

    def get(self, request, pk):
        id_peg = pk
        peg = Employee.objects.filter(id=id_peg).last()
        form = EditEmployeeForm(instance=peg)

        context={
            'object': peg,
            'form': form,
        }
        return render(request, self.template_name, context)


    def post(self, request, pk):
        pegawai = Employee.objects.filter(id=pk).last()
        form = EditEmployeeForm(request.POST, request.FILES, instance=pegawai)
        if request.FILES:
            delete_model(request, pk)

        if form.is_valid():
            print("valid")
            Itterasi.pegawai_itter = Itterasi.pegawai_itter + 1
            form.save()

        context={
            'form': EmployeeForm,
        }
        return redirect(self.success_url)


class PengaturanView(UpdateView):
    """To Page Daftar Hadir"""

    model = Kamera
    success_url = '/pengaturan/1/'
    template_name_suffix = '_update_form'
    fields = [
        'periode_absensi',
        'min_face_size',
        'face_threshold',
        'true_threshold',
        'input_width',
        'input_height',
    ]

    def post(self, request, pk):
        for_kamera = request.POST.get('for-camera')
        if for_kamera == None:
            for_kamera = pk
        list_kamera = Kamera.objects.all()
        kamera = Kamera.objects.filter(id=for_kamera).last()
        form = KameraForm(request.POST, instance=kamera)

        if form.is_valid():
            Itterasi.pengaturan_itter = Itterasi.pengaturan_itter + 1
            form.save()

        context={
            'kamera': kamera,
            'list_kamera': list_kamera,
            'for_kamera': for_kamera,
            'form': KameraForm,
        }

templates/misweb/employee_form.html
{% extends 'base.html' %}
{% block title %}Tambah Pegawai{% endblock %}
{% block content %}
{% if user.is_authenticated and user.is_staff %}
{% load static %}
{% include 'components/navbar.html' %}


<div class="container p-4">
    <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
            <div class="card bg-secondary border-0 mb-0">
                <div class="card-body px-lg-5 py-lg-5">
                <span class="row justify-content-center"><i class="fas fa-id-card fa-4x"></i>
                </span>
                    <h1 class="text-center p-4">Tambah Pegawai</h1>

                    <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}

                        <div class="form-group mb-3">
                            <div class="input-group input-group-merge input-group-alternative">

                                
                                <input
                                class="form-control"
                                id="{{ field.id_for_label }}"
                                name="{{ field.html_name }}"
                                placeholder="{{ field.label }}"
                                {% if field.label == 'Nip' %}
                                style="-webkit-appearance: none;-moz-appearance: textfield;"
                                {% endif %}

                                type="{% if field.label == 'Password' or field.label == 'Password confirmation' %}password{% elif field.label == 'Image' %}file{% elif field.label == 'Nip' %}number{% endif %}"
                                />                            

                                {{ field.errors }}

                            </div>
                        </div>

                    {% endfor %}


                        <div class="row mt-4 justify-content-end">
                            <a href="{% url 'list-pegawai' %}" class="btn btn-danger mr-4">Batal</a>
                            <button type="submit" class="btn btn-primary">Tambah</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        
    </div>
</div>


{% else %}
{% include 'components/not_authenticated.html' %}
{% endif %}
{% endblock %}

templates/misweb/kamera_update_form.html
{% extends 'base.html' %}
{% block title %}Pengaturan{% endblock %}
{% block content %}
{% if user.is_authenticated and user.is_staff %}
{% load static %}
{% include 'components/navbar.html' %}


    <div class="container-fluid mt-4">
      <div class="row">
        <div class="col-xl-12">
          <div class="card">

            <div class="card-header border-0">
                <div class="row align-items-center">
                    <div class="col-5">
                        <h2 class="mb-0">Pengaturan</h2>
                    </div>
                    <div class="col-3 text-right">
                        <span class="mb-0">Simpan Pengaturan untuk:</span>
                    </div>
                    <div class="col-4">
                        <form class="d-flex" method="POST">
                        {% csrf_token %}
    
                            <select class="form-control form-control-sm mx-2" id="for-camera" name="for-camera" placeholder="hii">
                            {% for cam in list_kamera %}
                                <option value="{{ cam.id }}" {% if cam.id == kamera.id %} selected {% endif %}>{{ cam.nama_kamera }}</option>
                            {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-primary btn-sm">Filter</button>
                        </form>
                    </div>                
                </div>
            </div>

            <form autocomplete="off" role="form"  method="POST" enctype="multipart/form-data">
                <div class="p-4">
                {% csrf_token %}

                {% for field in form %}

                    {% if field.label == 'Periode absensi' %}
                        <div class="row my-2">
                            <div class="col-4 my-auto">
                                <span>Periode Absensi</span>                
                            </div>
                            <input
                            type="hidden" class="form-control"
                            id="{{ field.id_for_label }}"
                            name="{{ field.html_name }}"
                            value="{{ field.value }}"
                            min="10" max="90">

                            <div class="col-1 d-flex flex-column">
                                <span class="badge badge-primary mt-2 mb-3">Hari</span>                
                                <span class="badge badge-primary mt-1 mb-2">Mulai</span>
                                <span class="badge badge-primary my-2">Selesai</span>
                            </div>

                            <div class="col-7">
                                <div id="businessHoursContainer1"></div>
                                <div class="clean">&nbsp;</div>
                            </div>

                        </div>
                    {{ field.errors }}
                            
                    {% elif field.label == 'Min face size' %}
                        <div class="row my-4">
                            <div class="col-5 my-auto">
                                <span>Ukuran Wajah Minimal</span>                
                            </div>
                            <div class="col-md-auto">
                                <div class="input-group input-group-sm">
                                    <input
                                    type="number" class="form-control"
                                    id="{{ field.id_for_label }}"
                                    name="{{ field.html_name }}"
                                    value="{{ field.value }}"
                                    min="10" max="90">
                                    <div class="input-group-append">
                                        <span class="input-group-text" style="line-height: 1;" id="inputGroup-sizing-sm">% dari ukuran input kamera</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {{ field.errors }}

                    {% elif field.label == 'Face threshold' %}
                        <div class="row my-4">
                            <div class="col-5 my-auto">
                                <span>Ambang batas deteksi wajah</span>                
                            </div>
                            <div class="col-2">
                                <input
                                type="number" class="form-control form-control-sm"
                                id="{{ field.id_for_label }}"
                                name="{{ field.html_name }}"
                                value="{{ field.value }}"
                                step=".01" min="0.1" max="0.9">
                            </div>
                        </div>
                    {{ field.errors }}

                    {% elif field.label == 'True threshold' %}
                        <div class="row my-4">
                            <div class="col-5 my-auto">
                                <span>Ambang batas deteksi keaslian</span>                
                            </div>
                            <div class="col-2">
                                <input
                                type="number" class="form-control form-control-sm"
                                id="{{ field.id_for_label }}"
                                name="{{ field.html_name }}"
                                value="{{ field.value }}"
                                step=".01" min="0.1" max="0.9">
                            </div>
                        </div>
                    {{ field.errors }}

                    {% elif field.label == 'Input width'%}
                        <div class="row">
                            <div class="col-4 my-auto">
                                <span>Ukuran input kamera</span>                
                            </div>

                            <div class="col-1 d-flex flex-column">
                                <span class="badge badge-primary my-2">Width</span>
                            </div>
                            <div class="col-md-auto">
                                <div class="input-group input-group-sm mb-3">
                                    <input
                                    type="number" class="form-control"
                                    id="{{ field.id_for_label }}"
                                    name="{{ field.html_name }}"
                                    value="{{ field.value }}"
                                    step="10" min="320" max="1920">
                                    <div class="input-group-append">
                                        <span class="input-group-text" style="line-height: 1;" id="inputGroup-sizing-sm">Px</span>
                                    </div>
                                </div>
                            </div>
                        {{ field.errors }}


                        {% elif field.label == 'Input height'%}
                            <div class="col-1 d-flex flex-column">
                                <span class="badge badge-primary my-2">Height</span>
                            </div>
                            <div class="col-md-auto">
                                <div class="input-group input-group-sm mb-3">
                                    <input
                                    type="number" class="form-control"
                                    id="{{ field.id_for_label }}"
                                    name="{{ field.html_name }}"
                                    value="{{ field.value }}"
                                    step="10" min="180" max="1080">
                                    <div class="input-group-append">
                                        <span class="input-group-text" style="line-height: 1;" id="inputGroup-sizing-sm">Px</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {{ field.errors }}
                        
                    {% endif %}
                {% endfor %}
                </div>
                <div class="d-flex flex-row-reverse p-4">
                    <button type="submit" class="btn btn-success" id="btn-simpan">Simpan</button>
                    <button type="button" class="btn btn-primary mx-4" id="setdefault">Kembali ke Default</button>
                </div>
            </form>
          </div> <!--card-->
        </div>

        {% include 'components/footer.html' %}

      </div>
    </div>

    <script >
        (function() {
            Rainbow.color();
            var jadwal_str = "{{kamera.periode_absensi}}";
            var jadwal = jQuery.parseJSON(jadwal_str.replace(/&quot;/ig,'"'));

            var businessHoursManager1 = $("#businessHoursContainer1").businessHours({
              dayTmpl: '<div class="dayContainer" style="width: 80px;">' +
                        '<div data-original-title="" class="colorBox" style="height: 20px;"><input type="checkbox" class="invisible operationState"/></div>' +
                        '<div class="weekday"></div>' +
                        '<div class="operationDayTimeContainer">' +
                        '<div class="operationTime input-group"><input type="text" name="startTime" class="form-control form-control-sm operationTimeFrom" value=""/></div>' +
                        '<div class="operationTime input-group"><input type="text" name="endTime" class="form-control form-control-sm operationTimeTill" value=""/></div>' +
                        '</div></div>',
              operationTime: jadwal,
                        });

            $("#setdefault").click(function() {
                jadwal_str = "[{&quot;isActive&quot;:true,&quot;timeFrom&quot;:&quot;07:00&quot;,&quot;timeTill&quot;:&quot;09:00&quot;},{&quot;isActive&quot;:true,&quot;timeFrom&quot;:&quot;07:00&quot;,&quot;timeTill&quot;:&quot;09:00&quot;},{&quot;isActive&quot;:true,&quot;timeFrom&quot;:&quot;07:00&quot;,&quot;timeTill&quot;:&quot;09:00&quot;},{&quot;isActive&quot;:true,&quot;timeFrom&quot;:&quot;07:00&quot;,&quot;timeTill&quot;:&quot;09:00&quot;},{&quot;isActive&quot;:true,&quot;timeFrom&quot;:&quot;07:00&quot;,&quot;timeTill&quot;:&quot;09:00&quot;},{&quot;isActive&quot;:false,&quot;timeFrom&quot;:null,&quot;timeTill&quot;:null},{&quot;isActive&quot;:false,&quot;timeFrom&quot;:null,&quot;timeTill&quot;:null}]";
                jadwal = jQuery.parseJSON(jadwal_str.replace(/&quot;/ig,'"'));
                $("#businessHoursContainer1").businessHours({
                    dayTmpl: '<div class="dayContainer" style="width: 80px;">' +
                                '<div data-original-title="" class="colorBox" style="height: 20px;"><input type="checkbox" class="invisible operationState"/></div>' +
                                '<div class="weekday"></div>' +
                                '<div class="operationDayTimeContainer">' +
                                '<div class="operationTime input-group"><input type="text" name="startTime" class="form-control form-control-sm operationTimeFrom" value=""/></div>' +
                                '<div class="operationTime input-group"><input type="text" name="endTime" class="form-control form-control-sm operationTimeTill" value=""/></div>' +
                                '</div></div>',
                    operationTime: jadwal,
                });
                $("#id_min_face_size").val("15");
                $("#id_face_threshold").val("0.4");
                $("#id_true_threshold").val("0.6");
                $("#id_input_width").val("640");
                $("#id_input_height").val("360");
            });

            $("#btn-simpan").click(function() {
                $("#id_periode_absensi").val(JSON.stringify(businessHoursManager1.serialize()));
            });

            var businessHoursManager2 = $("#businessHoursContainer2").businessHours({
                checkedColorClass: "workingBusinssDay",
                inputDisabled: true,
                uncheckedColorClass: "dayOff",
                dayTmpl: '<div class="dayContainer">' +
                        '<div data-original-title="" class="colorBox"><input type="checkbox" class="invisible operationState"/></div>' +
                        '<div class="weekday"></div></div>'
            });

            var b3 = $("#businessHoursContainer3");
            var businessHoursManagerBootstrap = b3.businessHours({
                postInit:function(){
                    b3.find('.operationTimeFrom, .operationTimeTill').timepicker({
                        'timeFormat': 'H:i',
                        'step': 15
                    });
                },
                dayTmpl: '<div class="dayContainer" style="width: 80px;">' +
                        '<div data-original-title="" class="colorBox"><input type="checkbox" class="invisible operationState"/></div>' +
                        '<div class="weekday"></div>' +
                        '<div class="operationDayTimeContainer">' +
                        '<div class="operationTime input-group"><span class="input-group-addon"><i class="fa fa-sun-o"></i></span><input type="text" name="startTime" class="mini-time form-control operationTimeFrom" value=""/></div>' +
                        '<div class="operationTime input-group"><span class="input-group-addon"><i class="fa fa-moon-o"></i></span><input type="text" name="endTime" class="mini-time form-control operationTimeTill" value=""/></div>' +
                        '</div></div>'
            });
        })();
    </script>


{% else %}
{% include 'components/not_authenticated.html' %}
{% endif %}
{% endblock %}